### ISSUE TITLE
Eliminar archivo que setea ModulePath

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/huayra-marble#1]
En la imagen 2014 con Huayra 2.x para las mablepoint el driver de intel iba compilado, se instalaba en /usr/local en vez de /usr, para eso se agregṕ en /etc/X11/xorg.conf.d un archivo para setear el ModulePath que busque en /usr/local.

Este archivo debe ser eliminado si existe, sino se intentan cargar el driver viejo que tiene un ABI diferente.

**Comment by matiasdelellis** [comment]
Fer,
No existe ningun archivo en /etc/X11/xorg.conf.d mas alla del de sna. Busque tambien en el historial. ¿Sera previo a subirlo a gihtub?

**Comment by matiasdelellis** [comment]
p.s: Tampoco ningun script q setee el archivo a mano.. :cry:

**Comment by ftoledo** [comment]
Este archivo estaba generado a mano en la imagen 2014. No estaba en ningún paquete.
